#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_Plantilla")]
	public partial class BDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertHeroes(Heroes instance);
    partial void UpdateHeroes(Heroes instance);
    partial void DeleteHeroes(Heroes instance);
    #endregion
		
		public BDDataContext() : 
				base(global::Datos.Properties.Settings.Default.db_PlantillaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public BDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public BDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Heroes> Heroes
		{
			get
			{
				return this.GetTable<Heroes>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ActualizarHeroe")]
		public int ActualizarHeroe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> valor1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string valor2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string valor3, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string valor4, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string valor5, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string valor6, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string valor7)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor1, valor2, valor3, valor4, valor5, valor6, valor7);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.EliminarHeroe")]
		public int EliminarHeroe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> valor1)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor1);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertarHeroe")]
		public int InsertarHeroe([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> valor1, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string valor2, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string valor3, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(500)")] string valor4, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(1000)")] string valor5, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string valor6, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(100)")] string valor7)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor1, valor2, valor3, valor4, valor5, valor6, valor7);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarHeroes")]
		public ISingleResult<ListarHeroesResult> ListarHeroes()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ListarHeroesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ListarHeroes_Filtro")]
		public ISingleResult<ListarHeroes_FiltroResult> ListarHeroes_Filtro([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Valor", DbType="VarChar(40)")] string valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<ListarHeroes_FiltroResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ObtenerHeroe_ID")]
		public ISingleResult<ObtenerHeroe_IDResult> ObtenerHeroe_ID([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> valor)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), valor);
			return ((ISingleResult<ObtenerHeroe_IDResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Heroes")]
	public partial class Heroes : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _HeroID;
		
		private string _RealName;
		
		private string _Alias;
		
		private string _Abilities;
		
		private string _History;
		
		private string _Seasons;
		
		private string _ActorName;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHeroIDChanging(int value);
    partial void OnHeroIDChanged();
    partial void OnRealNameChanging(string value);
    partial void OnRealNameChanged();
    partial void OnAliasChanging(string value);
    partial void OnAliasChanged();
    partial void OnAbilitiesChanging(string value);
    partial void OnAbilitiesChanged();
    partial void OnHistoryChanging(string value);
    partial void OnHistoryChanged();
    partial void OnSeasonsChanging(string value);
    partial void OnSeasonsChanged();
    partial void OnActorNameChanging(string value);
    partial void OnActorNameChanged();
    #endregion
		
		public Heroes()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeroID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int HeroID
		{
			get
			{
				return this._HeroID;
			}
			set
			{
				if ((this._HeroID != value))
				{
					this.OnHeroIDChanging(value);
					this.SendPropertyChanging();
					this._HeroID = value;
					this.SendPropertyChanged("HeroID");
					this.OnHeroIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(100)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this.OnRealNameChanging(value);
					this.SendPropertyChanging();
					this._RealName = value;
					this.SendPropertyChanged("RealName");
					this.OnRealNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="NVarChar(100)")]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this.OnAliasChanging(value);
					this.SendPropertyChanging();
					this._Alias = value;
					this.SendPropertyChanged("Alias");
					this.OnAliasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abilities", DbType="NVarChar(500)")]
		public string Abilities
		{
			get
			{
				return this._Abilities;
			}
			set
			{
				if ((this._Abilities != value))
				{
					this.OnAbilitiesChanging(value);
					this.SendPropertyChanging();
					this._Abilities = value;
					this.SendPropertyChanged("Abilities");
					this.OnAbilitiesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_History", DbType="NVarChar(1000)")]
		public string History
		{
			get
			{
				return this._History;
			}
			set
			{
				if ((this._History != value))
				{
					this.OnHistoryChanging(value);
					this.SendPropertyChanging();
					this._History = value;
					this.SendPropertyChanged("History");
					this.OnHistoryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seasons", DbType="NVarChar(50)")]
		public string Seasons
		{
			get
			{
				return this._Seasons;
			}
			set
			{
				if ((this._Seasons != value))
				{
					this.OnSeasonsChanging(value);
					this.SendPropertyChanging();
					this._Seasons = value;
					this.SendPropertyChanged("Seasons");
					this.OnSeasonsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActorName", DbType="NVarChar(100)")]
		public string ActorName
		{
			get
			{
				return this._ActorName;
			}
			set
			{
				if ((this._ActorName != value))
				{
					this.OnActorNameChanging(value);
					this.SendPropertyChanging();
					this._ActorName = value;
					this.SendPropertyChanged("ActorName");
					this.OnActorNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class ListarHeroesResult
	{
		
		private int _HeroID;
		
		private string _RealName;
		
		private string _Alias;
		
		private string _Abilities;
		
		private string _History;
		
		private string _Seasons;
		
		private string _ActorName;
		
		public ListarHeroesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeroID", DbType="Int NOT NULL")]
		public int HeroID
		{
			get
			{
				return this._HeroID;
			}
			set
			{
				if ((this._HeroID != value))
				{
					this._HeroID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(100)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this._RealName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="NVarChar(100)")]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this._Alias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abilities", DbType="NVarChar(500)")]
		public string Abilities
		{
			get
			{
				return this._Abilities;
			}
			set
			{
				if ((this._Abilities != value))
				{
					this._Abilities = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_History", DbType="NVarChar(1000)")]
		public string History
		{
			get
			{
				return this._History;
			}
			set
			{
				if ((this._History != value))
				{
					this._History = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seasons", DbType="NVarChar(50)")]
		public string Seasons
		{
			get
			{
				return this._Seasons;
			}
			set
			{
				if ((this._Seasons != value))
				{
					this._Seasons = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActorName", DbType="NVarChar(100)")]
		public string ActorName
		{
			get
			{
				return this._ActorName;
			}
			set
			{
				if ((this._ActorName != value))
				{
					this._ActorName = value;
				}
			}
		}
	}
	
	public partial class ListarHeroes_FiltroResult
	{
		
		private int _HeroID;
		
		private string _RealName;
		
		private string _Alias;
		
		private string _Abilities;
		
		private string _History;
		
		private string _Seasons;
		
		private string _ActorName;
		
		public ListarHeroes_FiltroResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeroID", DbType="Int NOT NULL")]
		public int HeroID
		{
			get
			{
				return this._HeroID;
			}
			set
			{
				if ((this._HeroID != value))
				{
					this._HeroID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(100)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this._RealName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="NVarChar(100)")]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this._Alias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abilities", DbType="NVarChar(500)")]
		public string Abilities
		{
			get
			{
				return this._Abilities;
			}
			set
			{
				if ((this._Abilities != value))
				{
					this._Abilities = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_History", DbType="NVarChar(1000)")]
		public string History
		{
			get
			{
				return this._History;
			}
			set
			{
				if ((this._History != value))
				{
					this._History = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seasons", DbType="NVarChar(50)")]
		public string Seasons
		{
			get
			{
				return this._Seasons;
			}
			set
			{
				if ((this._Seasons != value))
				{
					this._Seasons = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActorName", DbType="NVarChar(100)")]
		public string ActorName
		{
			get
			{
				return this._ActorName;
			}
			set
			{
				if ((this._ActorName != value))
				{
					this._ActorName = value;
				}
			}
		}
	}
	
	public partial class ObtenerHeroe_IDResult
	{
		
		private int _HeroID;
		
		private string _RealName;
		
		private string _Alias;
		
		private string _Abilities;
		
		private string _History;
		
		private string _Seasons;
		
		private string _ActorName;
		
		public ObtenerHeroe_IDResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HeroID", DbType="Int NOT NULL")]
		public int HeroID
		{
			get
			{
				return this._HeroID;
			}
			set
			{
				if ((this._HeroID != value))
				{
					this._HeroID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RealName", DbType="NVarChar(100)")]
		public string RealName
		{
			get
			{
				return this._RealName;
			}
			set
			{
				if ((this._RealName != value))
				{
					this._RealName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Alias", DbType="NVarChar(100)")]
		public string Alias
		{
			get
			{
				return this._Alias;
			}
			set
			{
				if ((this._Alias != value))
				{
					this._Alias = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Abilities", DbType="NVarChar(500)")]
		public string Abilities
		{
			get
			{
				return this._Abilities;
			}
			set
			{
				if ((this._Abilities != value))
				{
					this._Abilities = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_History", DbType="NVarChar(1000)")]
		public string History
		{
			get
			{
				return this._History;
			}
			set
			{
				if ((this._History != value))
				{
					this._History = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Seasons", DbType="NVarChar(50)")]
		public string Seasons
		{
			get
			{
				return this._Seasons;
			}
			set
			{
				if ((this._Seasons != value))
				{
					this._Seasons = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ActorName", DbType="NVarChar(100)")]
		public string ActorName
		{
			get
			{
				return this._ActorName;
			}
			set
			{
				if ((this._ActorName != value))
				{
					this._ActorName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
